### ISSUE TITLE
CPU count detection works wrong

### ISSUE THREAD

**Issue by torkve** [jgraph/draw-image-export2#11]
Latest commit [introduced](https://github.com/jgraph/draw-image-export2/blob/d9b7ed2f634c31c24fbd33dd033c7c9a7ad40c5f/export.js#L19) pool of workers, based on `os.cpus().length`.
This features works wrong in Linux containers, where it may see all the physical cores (e.g. 32), but the container is limited to a lesser value (e.g. 1), and thus it creates unreasonably large pool.

More reliable detection for containers would be to attempt to read something like `/sys/fs/cgroup/cpu/cpu.cfs_quota_us` and `/sys/fs/cgroup/cpu/cpu.cfs_period_us`, but the more simple and straightforward way would be to just support passing pool size via some environment variable, something like `process.env.WORKER_POOL_SIZE`.

Could you support it please?

**Comment by m-mohamedin** [comment]
OK, we went with WORKER_POOL_SIZE for simplicity and not being platform specific
Thanks for the suggestion
