### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by FlorianLudwig** [jgraph/draw-image-export2#8]
A collection of questions after reading the README:

> The 2018 server-side PNG/PDF export

Does the "2018" part mean it is deprecated?

> Updating internal draw.io versions
> su chrome

Why do I have to have a user called chrome?

> Usage

Well, I thought this is to render drawio files int png/pdf files.  It looks like rendering any html into png/pdf, is that correct? If so how do i turn a `.drawio` into a html?

My use case is the same as this one here: https://github.com/jgraph/drawio-desktop/issues/127#issuecomment-520125076

**Comment by davidjgraph** [comment]
No, it's just the year we wrote it.

You don't have a user called chrome, that's our internal notes.

**Comment by FlorianLudwig** [comment]
hi @davidjgraph thank you for the quick response. What about the last question? Is there some docs how to render a `.drawio`?

**Comment by davidjgraph** [comment]
Not using the image export server. You could export to the SVG and put that in an HTML page.
